<h2>Exceptions</h2>
<hr>
<h4 id="throw"><code>throw</code></h4>
<p>Use the <code>throw</code> operator to throw an exception:</p>
<pre><code>\Error 'something went wrong' throw
</code></pre>
<p>The exception need not be an <code>Error</code> object, it can be anything:</p>
<pre><code>@ 5 6 7 throw
</code></pre>
<hr>
<h4 id="try"><code>try</code>, <code>asyncTry</code></h4>
<p>The single operand of <code>try</code> is the <a href="?Syntax#open-scope">body</a>. The code in the body is executed; if it throws, <code>try</code> immediately returns whatever was thrown:</p>
<pre><code>// prints 1, returns the Error object (2 is not printed)
try
    print 1
    \Error 'something went wrong' throw
    print 2
</code></pre>
<p>If the body of <code>try</code> does not throw, <code>try</code> returns <code>undefined</code>.</p>
<p><code>asyncTry</code> is the asynchronous version of <code>try</code>. <code>asyncTry</code> returns a promise that resolves to whatever was thrown, or <code>undefined</code> if nothing was thrown. <code>await</code> can be used in the body of <code>asyncTry</code> â€” see <a href="#catch"><code>catch</code></a> for an example.</p>
<hr>
<h4 id="catch"><code>catch</code>, <code>asyncCatch</code></h4>
<p><code>catch</code> takes three operands:</p>
<ul>
<li>an expression: typically an application of <a href="#try"><code>try</code></a></li>
<li>a parameter: takes the value of the expression (the parameter is local to the body)</li>
<li>a <a href="?Syntax#open-scope">body</a></li>
</ul>
<p>The body is only executed if the <code>try</code> expression is truthy:</p>
<pre><code>// prints 'something went wrong!'
try
    \Error 'something went wrong' throw
| catch err
    + (err :message)'!' print
</code></pre>
<p><code>catch</code> returns <code>undefined</code>.</p>
<p>Here is an example of using <code>catch</code> with <a href="#try"><code>asyncTry</code></a>:</p>
<pre><code>// waits 1000 ms, prints 'something went wrong!'
asyncScope
    asyncTry
        period 1000 await
        \Error 'something went wrong' throw
    | await catch err
        + (err :message)'!' print
</code></pre>
<p><code>asyncCatch</code> is the asynchronous version of <code>catch</code>. <code>asyncCatch</code> returns a promise that resolves to <code>undefined</code>. <code>await</code> can be used in the body of <code>asyncCatch</code>.</p>


<br><br><br>